version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/

hooks:
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 300
      runas: root

  ApplicationStop:
    - location: scripts/stop_container.sh
      timeout: 300
      runas: root

